//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _28199014_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int cid { get; set; }
        public string breed { get; set; }
        public string cgender { get; set; }
        public string csize { get; set; }
        public string cfur { get; set; }
        public string color { get; set; }
        public string country { get; set; }
        public string cage { get; set; }
        public string lifeTime { get; set; }
        public string cpic { get; set; }
        public string cthumbnail { get; set; }
        public string nickname { get; set; }
        public string discription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
